In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('/content/drive/MyDrive/goods_dataset.csv')

In [8]:
df

,record_id,product_id,product_name,category,store_id,region,transaction_date,expiration_date,shelf_life_days,storage_temp,base_price,cost_price,initial_quantity,is_weekend,month,daily_demand,quality_grade,discount_pct,selling_price,units_sold,units_wasted,waste_pct,revenue,waste_cost,profit
0,1,BAK_DON_743,Donuts,Bakery,STORE_046,West,2024-09-25,2024-09-29,4,21.0,2.60,1.22,158,0,9,54,A,0.00,2.60,138,20,12.7,358.80,24.40,166.04
1,2,MEA_SAU_338,Sausages,Meat,STORE_030,Southwest,2023-04-14,2023-04-21,9,0.7,8.25,4.18,353,0,4,55,A,0.00,8.25,251,102,28.9,2070.75,426.36,595.21
2,3,BAK_BAG_799,Bagels,Bakery,STORE_035,Midwest,2024-10-25,2024-10-27,2,21.3,4.12,2.12,483,0,10,331,B,0.69,1.28,483,0,0.0,618.24,0.00,-405.72
3,4,PHA_VAC_801,Vaccines,Pharmaceuticals,STORE_003,Midwest,2023-11-29,2024-02-17,87,8.0,209.56,87.99,477,0,11,7,B,0.00,209.56,477,0,0.0,99960.12,0.00,57988.89
4,5,REA_FRE_422,Fresh Pasta,Ready_to_Eat,STORE_042,West,2023-08-06,2023-08-09,4,3.5,6.86,3.03,391,1,8,169,C,0.23,5.28,391,0,0.0,2064.48,0.00,879.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87351,97526,SEA_SAL_168,Salmon,Seafood,STORE_020,West,2023-09-23,2023-09-28,6,0.4,31.72,17.04,20,1,9,4,A,0.00,31.72,15,5,25.0,475.80,85.20,135.00
87352,97527,PHA_BIO_435,Biologics,Pharmaceuticals,STORE_004,Southeast,2024-11-01,2026-02-06,533,7.6,228.67,134.90,35,0,11,1,B,0.00,228.67,35,0,0.0,8003.45,0.00,3281.95
87353,97528,DEL_DIP_628,Dips,Deli,STORE_011,Southwest,2024-12-22,2024-12-27,5,3.5,12.10,4.96,149,1,12,53,A,0.00,12.10,149,0,0.0,1802.90,0.00,1063.86
87354,97530,MEA_CHI_709,Chicken,Meat,STORE_011,Southwest,2023-06-15,2023-06-21,9,1.8,12.28,6.31,472,0,6,65,B,0.00,12.28,264,208,44.1,3241.92,1312.48,263.60
87355,97532,FRO_FRO_484,Frozen Vegetables,Frozen_Meals,STORE_013,Northeast,2024-01-31,2024-07-11,210,-19.8,5.72,3.12,199,0,1,1,A,0.00,5.72,139,60,30.2,795.08,187.20,174.20

In [9]:
pd.set_option('display.max_columns', None)

In [10]:
df.head()

,record_id,product_id,product_name,category,store_id,region,transaction_date,expiration_date,shelf_life_days,storage_temp,base_price,cost_price,initial_quantity,is_weekend,month,daily_demand,quality_grade,discount_pct,selling_price,units_sold,units_wasted,waste_pct,revenue,waste_cost,profit
0,1,BAK_DON_743,Donuts,Bakery,STORE_046,West,2024-09-25,2024-09-29,4,21.0,2.60,1.22,158,0,9,54,A,0.00,2.60,138,20,12.7,358.80,24.40,166.04
1,2,MEA_SAU_338,Sausages,Meat,STORE_030,Southwest,2023-04-14,2023-04-21,9,0.7,8.25,4.18,353,0,4,55,A,0.00,8.25,251,102,28.9,2070.75,426.36,595.21
2,3,BAK_BAG_799,Bagels,Bakery,STORE_035,Midwest,2024-10-25,2024-10-27,2,21.3,4.12,2.12,483,0,10,331,B,0.69,1.28,483,0,0.0,618.24,0.00,-405.72
3,4,PHA_VAC_801,Vaccines,Pharmaceuticals,STORE_003,Midwest,2023-11-29,2024-02-17,87,8.0,209.56,87.99,477,0,11,7,B,0.00,209.56,477,0,0.0,99960.12,0.00,57988.89
4,5,REA_FRE_422,Fresh Pasta,Ready_to_Eat,STORE_042,West,2023-08-06,2023-08-09,4,3.5,6.86,3.03,391,1,8,169,C,0.23,5.28,391,0,0.0,2064.48,0.00,879.75

In [11]:
df.tail()

,record_id,product_id,product_name,category,store_id,region,transaction_date,expiration_date,shelf_life_days,storage_temp,base_price,cost_price,initial_quantity,is_weekend,month,daily_demand,quality_grade,discount_pct,selling_price,units_sold,units_wasted,waste_pct,revenue,waste_cost,profit
87351,97526,SEA_SAL_168,Salmon,Seafood,STORE_020,West,2023-09-23,2023-09-28,6,0.4,31.72,17.04,20,1,9,4,A,0.0,31.72,15,5,25.0,475.80,85.20,135.00
87352,97527,PHA_BIO_435,Biologics,Pharmaceuticals,STORE_004,Southeast,2024-11-01,2026-02-06,533,7.6,228.67,134.90,35,0,11,1,B,0.0,228.67,35,0,0.0,8003.45,0.00,3281.95
87353,97528,DEL_DIP_628,Dips,Deli,STORE_011,Southwest,2024-12-22,2024-12-27,5,3.5,12.10,4.96,149,1,12,53,A,0.0,12.10,149,0,0.0,1802.90,0.00,1063.86
87354,97530,MEA_CHI_709,Chicken,Meat,STORE_011,Southwest,2023-06-15,2023-06-21,9,1.8,12.28,6.31,472,0,6,65,B,0.0,12.28,264,208,44.1,3241.92,1312.48,263.60
87355,97532,FRO_FRO_484,Frozen Vegetables,Frozen_Meals,STORE_013,Northeast,2024-01-31,2024-07-11,210,-19.8,5.72,3.12,199,0,1,1,A,0.0,5.72,139,60,30.2,795.08,187.20,174.20

In [12]:
df.shape

(87356, 25)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87356 entries, 0 to 87355
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   record_id         87356 non-null  int64
 1   product_id        87356 non-null  object
 2   product_name      87356 non-null  object
 3   category          87356 non-null  object
 4   store_id          87356 non-null  object
 5   region            87356 non-null  object
 6   transaction_date  87356 non-null  object
 7   expiration_date   87356 non-null  object
 8   shelf_life_days   87356 non-null  int64
 9   storage_temp      87356 non-null  float64
 10  base_price        87356 non-null  float64
 11  cost_price        87356 non-null  float64
 12  initial_quantity  87356 non-null  int64
 13  is_weekend        87356 non-null  int64
 14  month             87356 non-null  int64
 15  daily_demand      87356 non-null  int64
 16  quality_grade     87356 non-null  object
 17  discount_pct      87356 non-null  float64
 18  selling_price     87356 non-null  float64
 19  units_sold        87356 non-null  int64
 20  units_wasted      87356 non-null  int64
 21  waste_pct         87356 non-null  float64
 22  revenue           87356 non-null  float64
 23  waste_cost        87356 non-null  float64
 24  profit            87356 non-null  float64
dtypes: float64(9), int64(8), object(8)
memory usage: 16.7+ MB

In [14]:
df.describe()

,record_id,shelf_life_days,storage_temp,base_price,cost_price,initial_quantity,is_weekend,month,daily_demand,discount_pct,selling_price,units_sold,units_wasted,waste_pct,revenue,waste_cost,profit
count,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000,87356.000000
mean,47744.872716,51.531332,3.855732,29.536282,16.166233,249.060122,0.294027,6.517824,60.313796,0.081983,28.103048,214.163126,34.896996,16.771621,6372.981666,443.932963,2275.955294
std,28492.832843,121.402404,8.896884,76.317103,42.501117,142.720318,0.455607,3.452896,81.175830,0.155652,74.612064,134.986905,49.132383,21.556797,20246.024951,2254.591311,8395.030290
min,1.000000,1.000000,-27.700000,1.000000,0.410000,10.000000,0.000000,1.000000,0.000000,0.000000,0.260000,0.000000,0.000000,0.000000,0.000000,0.000000,-499.940000
25%,22528.750000,5.000000,1.500000,5.860000,3.130000,123.000000,0.000000,4.000000,9.000000,0.000000,5.160000,99.000000,0.000000,0.000000,644.347500,0.000000,58.307500
50%,47498.500000,9.000000,4.100000,9.415000,5.090000,246.000000,0.000000,7.000000,33.000000,0.000000,8.400000,204.000000,7.000000,5.000000,1557.475000,25.600000,400.040000
75%,72456.250000,20.000000,6.800000,15.560000,8.480000,372.000000,1.000000,10.000000,80.000000,0.160000,14.350000,317.000000,58.000000,30.200000,3362.450000,271.250000,1164.405000
max,97532.000000,730.000000,27.700000,499.820000,346.610000,500.000000,1.000000,12.000000,1065.000000,0.750000,499.820000,500.000000,319.000000,100.000000,246243.640000,53215.980000,136195.210000

In [15]:
df_copy = df.copy()

In [16]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])
df['expiration_date'] = pd.to_datetime(df['expiration_date'])

In [17]:
df.dtypes

record_id                    int64
product_id                  object
product_name                object
category                    object
store_id                    object
region                      object
transaction_date    datetime64[ns]
expiration_date     datetime64[ns]
shelf_life_days              int64
storage_temp               float64
base_price                 float64
cost_price                 float64
initial_quantity             int64
is_weekend                   int64
month                        int64
daily_demand                 int64
quality_grade               object
discount_pct               float64
selling_price              float64
units_sold                   int64
units_wasted                 int64
waste_pct                  float64
revenue                    float64
waste_cost                 float64
profit                     float64
dtype: object

In [18]:
df.columns

Index(['record_id', 'product_id', 'product_name', 'category', 'store_id',
       'region', 'transaction_date', 'expiration_date', 'shelf_life_days',
       'storage_temp', 'base_price', 'cost_price', 'initial_quantity',
       'is_weekend', 'month', 'daily_demand', 'quality_grade', 'discount_pct',
       'selling_price', 'units_sold', 'units_wasted', 'waste_pct', 'revenue',
       'waste_cost', 'profit'],
      dtype='object')

In [19]:
df['category'].value_counts()

category
Produce            9919
Dairy              9904
Beverages          9849
Deli               9598
Bakery             9328
Meat               9244
Ready_to_Eat       8263
Seafood            7989
Pharmaceuticals    6672
Frozen_Meals       6590
Name: count, dtype: int64

In [20]:
df[df.duplicated()]

Empty DataFrame
Columns: [record_id, product_id, product_name, category, store_id, region, transaction_date, expiration_date, shelf_life_days, storage_temp, base_price, cost_price, initial_quantity, is_weekend, month, daily_demand, quality_grade, discount_pct, selling_price, units_sold, units_wasted, waste_pct, revenue, waste_cost, profit]
Index: []

In [21]:
df.shape

(87356, 25)

In [22]:
list(df.columns)

['record_id',
 'product_id',
 'product_name',
 'category',
 'store_id',
 'region',
 'transaction_date',
 'expiration_date',
 'shelf_life_days',
 'storage_temp',
 'base_price',
 'cost_price',
 'initial_quantity',
 'is_weekend',
 'month',
 'daily_demand',
 'quality_grade',
 'discount_pct',
 'selling_price',
 'units_sold',
 'units_wasted',
 'waste_pct',
 'revenue',
 'waste_cost',
 'profit']

In [23]:
#bad expiration

df[df["expiration_date"] < df["transaction_date"]]

Empty DataFrame
Columns: [record_id, product_id, product_name, category, store_id, region, transaction_date, expiration_date, shelf_life_days, storage_temp, base_price, cost_price, initial_quantity, is_weekend, month, daily_demand, quality_grade, discount_pct, selling_price, units_sold, units_wasted, waste_pct, revenue, waste_cost, profit]
Index: []

In [24]:
# bad pricing

df[(df["selling_price"] < 0) | (df["cost_price"] < 0) | (df["base_price"] < 0)]

Empty DataFrame
Columns: [record_id, product_id, product_name, category, store_id, region, transaction_date, expiration_date, shelf_life_days, storage_temp, base_price, cost_price, initial_quantity, is_weekend, month, daily_demand, quality_grade, discount_pct, selling_price, units_sold, units_wasted, waste_pct, revenue, waste_cost, profit]
Index: []

In [25]:
# bad quantity

df[(df["units_sold"] > df["initial_quantity"]) | (df["units_wasted"] > df["initial_quantity"])]

Empty DataFrame
Columns: [record_id, product_id, product_name, category, store_id, region, transaction_date, expiration_date, shelf_life_days, storage_temp, base_price, cost_price, initial_quantity, is_weekend, month, daily_demand, quality_grade, discount_pct, selling_price, units_sold, units_wasted, waste_pct, revenue, waste_cost, profit]
Index: []

In [26]:
df["profit_margin"] = np.where(
    df["revenue"] != 0,
    df["profit"] / df["revenue"],
    0
)

In [27]:
df["waste_rate"] = (df["units_wasted"] - df["initial_quantity"])

In [28]:
df["days_to_expiry"] = (df["expiration_date"] - df["transaction_date"]).dt.days

In [29]:
df

,record_id,product_id,product_name,category,store_id,region,transaction_date,expiration_date,shelf_life_days,storage_temp,base_price,cost_price,initial_quantity,is_weekend,month,daily_demand,quality_grade,discount_pct,selling_price,units_sold,units_wasted,waste_pct,revenue,waste_cost,profit,profit_margin,waste_rate,days_to_expiry
0,1,BAK_DON_743,Donuts,Bakery,STORE_046,West,2024-09-25,2024-09-29,4,21.0,2.60,1.22,158,0,9,54,A,0.00,2.60,138,20,12.7,358.80,24.40,166.04,0.462765,-138,4
1,2,MEA_SAU_338,Sausages,Meat,STORE_030,Southwest,2023-04-14,2023-04-21,9,0.7,8.25,4.18,353,0,4,55,A,0.00,8.25,251,102,28.9,2070.75,426.36,595.21,0.287437,-251,7
2,3,BAK_BAG_799,Bagels,Bakery,STORE_035,Midwest,2024-10-25,2024-10-27,2,21.3,4.12,2.12,483,0,10,331,B,0.69,1.28,483,0,0.0,618.24,0.00,-405.72,-0.656250,-483,2
3,4,PHA_VAC_801,Vaccines,Pharmaceuticals,STORE_003,Midwest,2023-11-29,2024-02-17,87,8.0,209.56,87.99,477,0,11,7,B,0.00,209.56,477,0,0.0,99960.12,0.00,57988.89,0.580120,-477,80
4,5,REA_FRE_422,Fresh Pasta,Ready_to_Eat,STORE_042,West,2023-08-06,2023-08-09,4,3.5,6.86,3.03,391,1,8,169,C,0.23,5.28,391,0,0.0,2064.48,0.00,879.75,0.426136,-391,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87351,97526,SEA_SAL_168,Salmon,Seafood,STORE_020,West,2023-09-23,2023-09-28,6,0.4,31.72,17.04,20,1,9,4,A,0.00,31.72,15,5,25.0,475.80,85.20,135.00,0.283733,-15,5
87352,97527,PHA_BIO_435,Biologics,Pharmaceuticals,STORE_004,Southeast,2024-11-01,2026-02-06,533,7.6,228.67,134.90,35,0,11,1,B,0.00,228.67,35,0,0.0,8003.45,0.00,3281.95,0.410067,-35,462
87353,97528,DEL_DIP_628,Dips,Deli,STORE_011,Southwest,2024-12-22,2024-12-27,5,3.5,12.10,4.96,149,1,12,53,A,0.00,12.10,149,0,0.0,1802.90,0.00,1063.86,0.590083,-149,5
87354,97530,MEA_CHI_709,Chicken,Meat,STORE_011,Southwest,2023-06-15,2023-06-21,9,1.8,12.28,6.31,472,0,6,65,B,0.00,12.28,264,208,44.1,3241.92,1312.48,263.60,0.081310,-264,6
87355,97532,FRO_FRO_484,Frozen Vegetables,Frozen_Meals,STORE_013,Northeast,2024-01-31,2024-07-11,210,-19.8,5.72,3.12,199,0,1,1,A,0.00,5.72,139,60,30.2,795.08,187.20,174.20,0.219097,-139,162

In [5]:
import plotly.express as px
import plotly.graph_objects as go

In [30]:
# Product Storage temperature

px.histogram(
    df,
    x='storage_temp',
    nbins=120,
    color_discrete_sequence=['#EF553B'],
    title='Storage Temperature Distribution',
).show()

In [31]:
# product count by category

fig = px.bar(
    df['category'].value_counts().reset_index(),
    x='count',
    y='category',
    orientation='h',
    color='category',
    title='Product Count by Category'
)

fig.update_xaxes(
    tickvals=[3000, 6000, 9000,],
    ticktext=['3k', '6k', '9k'],
    range=[0, 15000],
    title='Count'
)

fig.show()

In [32]:
df.head()

,record_id,product_id,product_name,category,store_id,region,transaction_date,expiration_date,shelf_life_days,storage_temp,base_price,cost_price,initial_quantity,is_weekend,month,daily_demand,quality_grade,discount_pct,selling_price,units_sold,units_wasted,waste_pct,revenue,waste_cost,profit,profit_margin,waste_rate,days_to_expiry
0,1,BAK_DON_743,Donuts,Bakery,STORE_046,West,2024-09-25,2024-09-29,4,21.0,2.60,1.22,158,0,9,54,A,0.00,2.60,138,20,12.7,358.80,24.40,166.04,0.462765,-138,4
1,2,MEA_SAU_338,Sausages,Meat,STORE_030,Southwest,2023-04-14,2023-04-21,9,0.7,8.25,4.18,353,0,4,55,A,0.00,8.25,251,102,28.9,2070.75,426.36,595.21,0.287437,-251,7
2,3,BAK_BAG_799,Bagels,Bakery,STORE_035,Midwest,2024-10-25,2024-10-27,2,21.3,4.12,2.12,483,0,10,331,B,0.69,1.28,483,0,0.0,618.24,0.00,-405.72,-0.656250,-483,2
3,4,PHA_VAC_801,Vaccines,Pharmaceuticals,STORE_003,Midwest,2023-11-29,2024-02-17,87,8.0,209.56,87.99,477,0,11,7,B,0.00,209.56,477,0,0.0,99960.12,0.00,57988.89,0.580120,-477,80
4,5,REA_FRE_422,Fresh Pasta,Ready_to_Eat,STORE_042,West,2023-08-06,2023-08-09,4,3.5,6.86,3.03,391,1,8,169,C,0.23,5.28,391,0,0.0,2064.48,0.00,879.75,0.426136,-391,3

In [33]:
# Monthly Trends

monthly = df.groupby("month", as_index=False)[
    ["revenue", "profit", "waste_cost"]
].sum()

fig = px.line(
    monthly,
    x="month",
    y=["revenue", "profit", "waste_cost"],
    title="Monthly Business Trends",
    markers=True
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Amount",
    legend_title="Metric"
)

fig.show()

In [34]:
# Monthly revenue

monthly_revenue = df.groupby("month", as_index=False)["revenue"].sum()

fig = px.line(
    monthly_revenue,
    x="month",
    y="revenue",
    title="Revenue by Month",
    markers=True
)

fig.update_layout(xaxis_title="Month", yaxis_title="Revenue")
fig.show()

In [35]:
# monthly profit

monthly_profit = df.groupby("month", as_index=False)["profit"].sum()

fig = px.line(
    monthly_profit,
    x="month",
    y="profit",
    title="Profit by Month",
    markers=True
)

fig.update_layout(xaxis_title="Month", yaxis_title="Profit")
fig.show()

In [36]:
# monthly waste

monthly_waste = df.groupby("month", as_index=False)["waste_cost"].sum()

fig = px.line(
    monthly_waste,
    x="month",

    y="waste_cost",
    title="Waste Cost by Month",
    markers=True
)

fig.update_layout(xaxis_title="Month", yaxis_title="Waste Cost")
fig.show()

In [37]:
# profit by category

cat_profit = df.groupby("category", as_index=False)["profit"].sum().sort_values("profit", ascending=False)
fig = px.bar(cat_profit, x="profit", y="category", color = 'category', orientation="h", title="Total Profit by Category")
fig.show()

In [38]:
# waste by category

waste_by_cat = df.groupby("category")["waste_cost"].sum().sort_values(ascending=False)
px.bar(waste_by_cat, title="Waste Cost by Category").show()

In [39]:
# lifespan by category

lifespan_by_cat = df.groupby("category")["shelf_life_days"].sum().sort_values(ascending=False)
px.bar(lifespan_by_cat, title="shelf_life_days by Category").show()

In [40]:
df.to_csv("goods_dataset2.csv", index=False)

In [41]:
from google.colab import files
files.download("goods_dataset2.csv")